folders: main.cpp MyStrings.cpp BaseFile.cpp File.cpp Folder.cpp FileTree.cpp FileIterator.cpp FileTreeConsoleInterface.cpp
	g++ -o folders main.cpp MyStrings.cpp BaseFile.cpp File.cpp Folder.cpp FileTree.cpp FileIterator.cpp FileTreeConsoleInterface.cpp -I.
